apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcapi
spec:
  selector:
    matchLabels:
      app: grpcapi
  template:
    metadata:
      labels:
        app: grpcapi
        v: c2
    spec:
      containers:
        - name: grpcapi
          image: rhiadciccoli/testapi:latest
          ports:
          - containerPort: 4040
---
apiVersion:  v1
kind: Service
metadata: 
  name: grpcapi-service
spec:
  selector:
    app: grpcapi
  ports:
  - protocol: TCP
    port: 4040
    targetPort: 4040