apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - git:
      repoURL: https://github.com/rhiadc1/gitops-api.git
      revision: HEAD
      files:
      - path: "config/**/config.json"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rhiadc1/gitops-api.git
        targetRevision: HEAD
        path: "config/apps"
      destination:
        server: '{{cluster.address}}'
        namespace: '{{path.basename}}'
