apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcapi1
spec:
  selector:
    matchLabels:
      app: grpcapi1
  template:
    metadata:
      labels:
        app: grpcapi1
        v: c1
    spec:
      containers:
        - name: grpcapi1
          image: rhiadciccoli/testapi:latest
          ports:
          - containerPort: 4040
---
apiVersion:  v1
kind: Service
metadata: 
  name: grpcapi-service1
spec:
  selector:
    app: grpcapi1
  ports:
  - protocol: TCP
    port: 4040
    targetPort: 4040
